services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: ["tini","--","jupyter","lab","--ip=0.0.0.0","--port=8888","--no-browser","--allow-root","--ServerApp.token="]

